Server:
  Host: localhost
  Port: 8080
  ReadTimeOut: 10
  WriteTimeOut: 10
  Mode: release

Database:
  User: root
  Password: admin
  Host: 127.0.0.1:3306
  DBName: dcard_service
  Table_Prefix: dcard_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30

App:
  NotAllowedAccessTime: 60 # in second
  LimiterBucketSize: 10
  LimiterTokenTime: 200 # in ms
  LimterClearTime: 60 # in second